name: test-build

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
permissions:
    contents: read
    id-token: write
jobs:
    test-build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4 #clona el repositorio 
        - name: Setup Node.js 24.x 
          uses: actions/setup-node@v4 ##descarga la version de node que se está usando en el repo 
          with:
              node-version: '24.x'
              cache: 'npm'
        - run: npm ci ##instala dependencias
        - run: npm test ##corre los tests
        - run: npm run build --if-present ##compila ts a js
