##https://developer.hashicorp.com/terraform/tutorials/automation/github-actions
name: 'Terraform'

on:
    push:
        branches: ["master"]
    pull_request: 
        branches: ["master"]

jobs:
    terraform:
        name: "Terraform Plan"
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        steps:
            - uses: actions/checkout@v4 
            - uses: hashicorp/setup-terraform@v3 ##instala terraform en el contenedor
            - uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}
            - run: terraform init ##descarga modulos necesarios
              working-directory: ./terraform
            - run: terraform validate
              working-directory: ./terraform
            - run: terraform plan -var="public_key_path=${{ secrets.TF_VAR_PUBLIC_KEY }}" ##muestra que recursos va a crear/destruir sin hacer nada en AWS, es increible
              working-directory: ./terraform
    
    terraform-apply:
        name: "Terraform Apply"
        needs: terraform
        environment: production
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4 
            - uses: hashicorp/setup-terraform@v3 ##instala terraform en el contenedor
            - uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}

            - run: terraform init
              working-directory: ./terraform
            - run: terraform apply -auto-approve -var="public_key_path=${{ secrets.TF_VAR_PUBLIC_KEY}}  
              working-directory: ./terraform